### ISSUE TITLE
Name collisions when building yices2

### ISSUE THREAD

**Issue by wenkokke** [SRI-CSL/homebrew-sri-csl#2]
Building `yices2` with [mht208/formal](https://github.com/mht208/homebrew-formal) tapped results in a name collision, as the `yices2` formula depends on an unqualified version of `cudd`.

Consider using fully qualified names in the dependencies for `yices2`, i.e.,
```ruby
depends_on "sri-csl/sri-csl/libpoly"
depends_on "sri-csl/sri-csl/cudd"
depends_on "sri-csl/sri-csl/cadical"
```

**Comment by ianamason** [comment]
Thanks. Fixed in 92567e30b6cce91a17a8f14b6d073879c1d6ca98.
